services:
  - type: web
    name: molecule-generator
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: unzip -o model.zip && gunicorn app:app --bind 0.0.0.0:8080
